export const START_FETCHING_PARTICIPANTS =
    "redux/categories/START_FETCHING_PARTICIPANTS";
export const SUCCESS_FETCHING_PARTICIPANTS =
    "redux/categories/SUCCESS_FETCHING_PARTICIPANTS";
export const ERROR_FETCHING_PARTICIPANTS =
    "redux/categories/ERROR_FETCHING_PARTICIPANTS";
